# Generated by Django 3.1.5 on 2021-06-21 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_sup',
            fields=[
                ('sup_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('org_id', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('lga', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('org_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=100)),
                ('job_desc', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('lga', models.CharField(max_length=200)),
                ('student_id', models.IntegerField(default=None)),
                ('sup_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('mon', models.CharField(max_length=200)),
                ('tue', models.TextField()),
                ('wed', models.EmailField(max_length=254)),
                ('thur', models.CharField(max_length=40)),
                ('fri', models.CharField(max_length=100)),
                ('mon_date', models.DateField()),
                ('tue_date', models.DateField()),
                ('wed_date', models.DateField()),
                ('thur_date', models.DateField()),
                ('fri_date', models.DateField()),
                ('student_id', models.TextField()),
                ('is_signed', models.BooleanField(default=False)),
                ('date_signed', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('matric', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.TextField()),
            ],
        ),
    ]
