# Generated by Django 3.1.5 on 2021-06-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210621_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fri',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='mon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='thur',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='wed',
            field=models.TextField(),
        ),
    ]
