# Generated by Django 3.1.5 on 2021-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210623_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_signed',
            field=models.DateField(),
        ),
    ]
