# Generated by Django 3.1.5 on 2021-06-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210623_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='student_id',
            field=models.TextField(default=None),
        ),
    ]
