# Generated by Django 3.1.5 on 2021-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210629_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sup_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
