# Generated by Django 3.1.5 on 2021-07-16 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_student_sup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('mes_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sup_id', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
