# Generated by Django 3.1.5 on 2021-07-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mes_id',
        ),
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
