# Generated by Django 3.1.5 on 2021-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210722_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_count',
            fields=[
                ('id', models.AutoField(default=None, editable=False, primary_key=True, serialize=False)),
                ('sup_id', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
