# Generated by Django 3.1.5 on 2021-07-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_message_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sup_id',
            field=models.TextField(default=''),
        ),
    ]
